name: CI Workflow

on:
  push:
    branches:
      - main  # ajuste conforme o nome da sua branch principal

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test -v ./...